// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 1.1.4322.573
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Mono Web Services Description Language Utility
//

/// <remarks/>
/// <remarks>
///Web Service providing access to the simias database.
///</remarks>
[System.Web.Services.WebServiceBinding(Name="Browser ServiceSoap",Namespace="http://novell.com/simias/browser"),
System.Diagnostics.DebuggerStepThroughAttribute(),
System.ComponentModel.DesignerCategoryAttribute("code")]
public class BrowserService : System.Web.Services.Protocols.SoapHttpClientProtocol {

    public BrowserService () {
        this.Url = "http://localhost:8086/simias10/SimiasBrowser.asmx";
    }

    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/browser/EnumerateCollections",RequestNamespace="http://novell.com/simias/browser",ResponseNamespace="http://novell.com/simias/browser",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public virtual BrowserNode[] EnumerateCollections() {
        System.Object[] results = this.Invoke("EnumerateCollections", new object[0]);
        return ((BrowserNode[])(results[0]));
    }

    public virtual System.IAsyncResult BeginEnumerateCollections(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("EnumerateCollections", new object[0], callback, asyncState);
    }

    public virtual BrowserNode[] EndEnumerateCollections(System.IAsyncResult asyncResult) {
        System.Object[] results = this.EndInvoke(asyncResult);
        return ((BrowserNode[])(results[0]));
    }

    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/browser/EnumerateNodes",RequestNamespace="http://novell.com/simias/browser",ResponseNamespace="http://novell.com/simias/browser",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public virtual BrowserNode[] EnumerateNodes(string collectionID) {
        System.Object[] results = this.Invoke("EnumerateNodes", new object[] {
            collectionID});
        return ((BrowserNode[])(results[0]));
    }

    public virtual System.IAsyncResult BeginEnumerateNodes(string collectionID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("EnumerateNodes", new object[] {
            collectionID}, callback, asyncState);
    }

    public virtual BrowserNode[] EndEnumerateNodes(System.IAsyncResult asyncResult) {
        System.Object[] results = this.EndInvoke(asyncResult);
        return ((BrowserNode[])(results[0]));
    }

    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/browser/GetCollectionByID",RequestNamespace="http://novell.com/simias/browser",ResponseNamespace="http://novell.com/simias/browser",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public virtual BrowserNode GetCollectionByID(string collectionID) {
        System.Object[] results = this.Invoke("GetCollectionByID", new object[] {
            collectionID});
        return ((BrowserNode)(results[0]));
    }

    public virtual System.IAsyncResult BeginGetCollectionByID(string collectionID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetCollectionByID", new object[] {
            collectionID}, callback, asyncState);
    }

    public virtual BrowserNode EndGetCollectionByID(System.IAsyncResult asyncResult) {
        System.Object[] results = this.EndInvoke(asyncResult);
        return ((BrowserNode)(results[0]));
    }

    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/browser/GetNodeByID",RequestNamespace="http://novell.com/simias/browser",ResponseNamespace="http://novell.com/simias/browser",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public virtual BrowserNode GetNodeByID(string collectionID, string nodeID) {
        System.Object[] results = this.Invoke("GetNodeByID", new object[] {
            collectionID,
            nodeID});
        return ((BrowserNode)(results[0]));
    }

    public virtual System.IAsyncResult BeginGetNodeByID(string collectionID, string nodeID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetNodeByID", new object[] {
            collectionID,
            nodeID}, callback, asyncState);
    }

    public virtual BrowserNode EndGetNodeByID(System.IAsyncResult asyncResult) {
        System.Object[] results = this.EndInvoke(asyncResult);
        return ((BrowserNode)(results[0]));
    }

    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/browser/ModifyProperty",RequestNamespace="http://novell.com/simias/browser",ResponseNamespace="http://novell.com/simias/browser",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public virtual void ModifyProperty(string collectionID, string nodeID, string propertyName, string propertyType, string oldPropertyValue, string newPropertyValue, uint propertyFlags) {
        this.Invoke("ModifyProperty", new object[] {
            collectionID,
            nodeID,
            propertyName,
            propertyType,
            oldPropertyValue,
            newPropertyValue,
            propertyFlags});
    }

    public virtual System.IAsyncResult BeginModifyProperty(string collectionID, string nodeID, string propertyName, string propertyType, string oldPropertyValue, string newPropertyValue, uint propertyFlags, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ModifyProperty", new object[] {
            collectionID,
            nodeID,
            propertyName,
            propertyType,
            oldPropertyValue,
            newPropertyValue,
            propertyFlags}, callback, asyncState);
    }

    public virtual void EndModifyProperty(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }

    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/browser/AddProperty",RequestNamespace="http://novell.com/simias/browser",ResponseNamespace="http://novell.com/simias/browser",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public virtual void AddProperty(string collectionID, string nodeID, string propertyName, string propertyType, string propertyValue, uint propertyFlags) {
        this.Invoke("AddProperty", new object[] {
            collectionID,
            nodeID,
            propertyName,
            propertyType,
            propertyValue,
            propertyFlags});
    }

    public virtual System.IAsyncResult BeginAddProperty(string collectionID, string nodeID, string propertyName, string propertyType, string propertyValue, uint propertyFlags, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AddProperty", new object[] {
            collectionID,
            nodeID,
            propertyName,
            propertyType,
            propertyValue,
            propertyFlags}, callback, asyncState);
    }

    public virtual void EndAddProperty(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }

    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/browser/DeleteProperty",RequestNamespace="http://novell.com/simias/browser",ResponseNamespace="http://novell.com/simias/browser",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public virtual void DeleteProperty(string collectionID, string nodeID, string propertyName, string propertyType, string propertyValue) {
        this.Invoke("DeleteProperty", new object[] {
            collectionID,
            nodeID,
            propertyName,
            propertyType,
            propertyValue});
    }

    public virtual System.IAsyncResult BeginDeleteProperty(string collectionID, string nodeID, string propertyName, string propertyType, string propertyValue, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteProperty", new object[] {
            collectionID,
            nodeID,
            propertyName,
            propertyType,
            propertyValue}, callback, asyncState);
    }

    public virtual void EndDeleteProperty(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }

    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/browser/DeleteCollection",RequestNamespace="http://novell.com/simias/browser",ResponseNamespace="http://novell.com/simias/browser",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public virtual void DeleteCollection(string collectionID) {
        this.Invoke("DeleteCollection", new object[] {
            collectionID});
    }

    public virtual System.IAsyncResult BeginDeleteCollection(string collectionID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteCollection", new object[] {
            collectionID}, callback, asyncState);
    }

    public virtual void EndDeleteCollection(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }

    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/browser/DeleteNode",RequestNamespace="http://novell.com/simias/browser",ResponseNamespace="http://novell.com/simias/browser",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public virtual void DeleteNode(string collectionID, string nodeID) {
        this.Invoke("DeleteNode", new object[] {
            collectionID,
            nodeID});
    }

    public virtual System.IAsyncResult BeginDeleteNode(string collectionID, string nodeID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteNode", new object[] {
            collectionID,
            nodeID}, callback, asyncState);
    }

    public virtual void EndDeleteNode(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlType(Namespace="http://novell.com/simias/browser")]
public class BrowserNode {

    /// <remarks/>
    public string NodeData;
}

