BUILD_DATE = 20031017
BUILD_OS = linux
CC = cc -c
CDEF = -D
CFLAGS = -pipe -Wall -W -DLINUX -DPRODUCT_NAME=denali -DPRODUCT_VERSION=0.1.0.20031017 -g -DDEBUG
CINC = -I
COUT = -o
CP = cp -f
CPU = i686
CSC = mcs
CSCFLAGS = /debug+ /d:DEBUG /d:TRACE /d:PRODUCT_NAME=denali /d:PRODUCT_VERSION=0.1.0.20031017
CXX = c++ -c
CXXFLAGS = -pipe -Wall -W -DLINUX -DPRODUCT_NAME=denali -DPRODUCT_VERSION=0.1.0.20031017 -g -DDEBUG
DEBUG = YES
DOCDIR = /home/rlyon/wa/denali/src/doc
EMPTY = 
EXE_EXT = 
FXCOP = @echo FxCop not available on Mono \#
FXCOP_FLAGS = 
LD = c++
LDFLAGS =  -g
LDINC = -L
LDOUT = -o 
LIBFLAG = -l
LIBS = 
LIB_EXT = 
LIB_PRE = lib
MAJOR_VERSION = 0
MINOR_VERSION = 1
MKDIR = mkdir
NDOC = mono $(TOOLDIR)/NDoc/bin/NDocConsole.exe
NDOC_FLAGS = 
NUNIT = mono $(TOOLDIR)/NUnit/bin/nunit-console.exe
NUNIT_FLAGS = /nologo
OBJ_EXT = .o
PACKAGE_RELEASE = 1
PATCH_LEVEL = 0
PLATFORM = mono
PRODUCT_NAME = denali
PRODUCT_VERSION = 0.1.0.20031017
REPORT = mono $(TOOLDIR)/Report/Report.exe
RM = rm -f
RMDIR = rm -rf
SEP = /
SHARED_LIB_EXT = .so
SHARED_LIB_FLAG = -shared
SHELL = bash
SLN2MK = mono $(TOOLDIR)/sln2mk/sln2mk.exe
SPACE = $(EMPTY) $(EMPTY)
SRCDIR = /home/rlyon/wa/denali/src
STAGE_DIR = /home/rlyon/wa/denali/src/stage
SYSTEM_XML = System.Xml.dll
TARGET_OS = linux
TOOLDIR = /home/rlyon/wa/denali/src/../tools
TOOLS = gnu
VPATH = /usr/lib
