#!/bin/sh -x
#Create the links in the framework to have it fit the normal Framework structure.
if [ -f /opt/novell/ifolder3/etc/simias-client-bootstrap.config ]; then
	echo "Updating /opt/novell/ifolder3/etc/simias-client-bootstrap.config"
	sed "s/assembly=\"Simias.Bonjour.dll\" enabled=\"False\"/assembly=\"Simias.Bonjour.dll\" enabled=\"True\"/" < /opt/novell/ifolder3/etc/simias-client-bootstrap.config > /opt/novell/ifolder3/etc/simias-client-bootstrap.config.new
	mv /opt/novell/ifolder3/etc/simias-client-bootstrap.config.new /opt/novell/ifolder3/etc/simias-client-bootstrap.config
else 
	echo "/opt/novell/ifolder3/etc/simias-client-bootstrap.config was not found"
fi

if [ -f ~/.local/share/simias/Simias.config ]; then
	echo "Updating ~/.local/share/simias/Simias.config"
	sed "s/assembly=\"Simias.Bonjour.dll\" enabled=\"False\"/assembly=\"Simias.Bonjour.dll\" enabled=\"True\"/" < ~/.local/share/simias/Simias.config > ~/.local/share/simias/Simias.config.new
	mv ~/.local/share/simias/Simias.config.new ~/.local/share/simias/Simias.config
else 
	echo "~/.local/share/simias/Simias.config was not found"
fi

