//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;


/// <remarks/>
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BrowserSoap", Namespace="http://tempuri.org/")]
public class Browser : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    /// <remarks/>
    public Browser() {
        this.Url = "http://localhost:8086/SimiasBrowser.asmx";
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnumerateCollections", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public BrowserNode[] EnumerateCollections() {
        object[] results = this.Invoke("EnumerateCollections", new object[0]);
        return ((BrowserNode[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginEnumerateCollections(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("EnumerateCollections", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public BrowserNode[] EndEnumerateCollections(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BrowserNode[])(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnumerateNodes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public BrowserNode[] EnumerateNodes(string collectionID) {
        object[] results = this.Invoke("EnumerateNodes", new object[] {
                    collectionID});
        return ((BrowserNode[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginEnumerateNodes(string collectionID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("EnumerateNodes", new object[] {
                    collectionID}, callback, asyncState);
    }
    
    /// <remarks/>
    public BrowserNode[] EndEnumerateNodes(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BrowserNode[])(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCollectionByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public BrowserNode GetCollectionByID(string collectionID) {
        object[] results = this.Invoke("GetCollectionByID", new object[] {
                    collectionID});
        return ((BrowserNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetCollectionByID(string collectionID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetCollectionByID", new object[] {
                    collectionID}, callback, asyncState);
    }
    
    /// <remarks/>
    public BrowserNode EndGetCollectionByID(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BrowserNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNodeByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public BrowserNode GetNodeByID(string collectionID, string nodeID) {
        object[] results = this.Invoke("GetNodeByID", new object[] {
                    collectionID,
                    nodeID});
        return ((BrowserNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetNodeByID(string collectionID, string nodeID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetNodeByID", new object[] {
                    collectionID,
                    nodeID}, callback, asyncState);
    }
    
    /// <remarks/>
    public BrowserNode EndGetNodeByID(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BrowserNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModifyProperty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void ModifyProperty(string collectionID, string nodeID, string propertyName, string propertyType, string oldPropertyValue, string newPropertyValue, System.UInt32 propertyFlags) {
        this.Invoke("ModifyProperty", new object[] {
                    collectionID,
                    nodeID,
                    propertyName,
                    propertyType,
                    oldPropertyValue,
                    newPropertyValue,
                    propertyFlags});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginModifyProperty(string collectionID, string nodeID, string propertyName, string propertyType, string oldPropertyValue, string newPropertyValue, System.UInt32 propertyFlags, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ModifyProperty", new object[] {
                    collectionID,
                    nodeID,
                    propertyName,
                    propertyType,
                    oldPropertyValue,
                    newPropertyValue,
                    propertyFlags}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndModifyProperty(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddProperty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void AddProperty(string collectionID, string nodeID, string propertyName, string propertyType, string propertyValue, System.UInt32 propertyFlags) {
        this.Invoke("AddProperty", new object[] {
                    collectionID,
                    nodeID,
                    propertyName,
                    propertyType,
                    propertyValue,
                    propertyFlags});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAddProperty(string collectionID, string nodeID, string propertyName, string propertyType, string propertyValue, System.UInt32 propertyFlags, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AddProperty", new object[] {
                    collectionID,
                    nodeID,
                    propertyName,
                    propertyType,
                    propertyValue,
                    propertyFlags}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndAddProperty(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteProperty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void DeleteProperty(string collectionID, string nodeID, string propertyName, string propertyType, string propertyValue) {
        this.Invoke("DeleteProperty", new object[] {
                    collectionID,
                    nodeID,
                    propertyName,
                    propertyType,
                    propertyValue});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteProperty(string collectionID, string nodeID, string propertyName, string propertyType, string propertyValue, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteProperty", new object[] {
                    collectionID,
                    nodeID,
                    propertyName,
                    propertyType,
                    propertyValue}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndDeleteProperty(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteCollection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void DeleteCollection(string collectionID) {
        this.Invoke("DeleteCollection", new object[] {
                    collectionID});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteCollection(string collectionID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteCollection", new object[] {
                    collectionID}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndDeleteCollection(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteNode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void DeleteNode(string collectionID, string nodeID) {
        this.Invoke("DeleteNode", new object[] {
                    collectionID,
                    nodeID});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteNode(string collectionID, string nodeID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteNode", new object[] {
                    collectionID,
                    nodeID}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndDeleteNode(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public class BrowserNode {
    
    /// <remarks/>
    public string NodeData;
}
