#!/bin/sh -x
#Create the links in the framework to have it fit the normal Framework structure.
if [ -d "/opt/novell/ifolder3/Applications/iFolder 3.app" ]; then
	if [ -d "/Applications/iFolder 3.app" ]; then
		rm -rf "/Applications/iFolder 3.app"
	fi
	mv -f "/opt/novell/ifolder3/Applications/iFolder 3.app" /Applications
	rm -rf /opt/novell/ifolder3/Applications
else 
	echo "iFolder.app was not found"
fi

