#!/bin/bash

# This is a lame script I had to make because Apple now returns a 1 when
# a package is successfully built.  Oh Very Nice Job there Idiots!

/Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker $@
if [ $? = 1 ]
then
	exit 0
else
	exit $?
fi
