#!/bin/sh
rm -rf RPM
mkdir RPM
echo %_topdir `pwd`/RPM > $HOME/.rpmmacros
mkdir -p RPM/BUILD
mkdir -p RPM/RPMS
mkdir -p RPM/SOURCES
mkdir -p RPM/SPECS
mkdir -p RPM/SRPMS
cp nautilus-mono.spec RPM/SPECS
cp nautilus-mono-0.1.0.tar.gz RPM/SOURCES
rpmbuild -ba RPM/SPECS/nautilus-mono.spec
