//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrayApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrayApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &quot;{0}&quot; to ....
        /// </summary>
        internal static string acceptDescription {
            get {
                return ResourceManager.GetString("acceptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while attempting to download the iFolder..
        /// </summary>
        internal static string acceptError {
            get {
                return ResourceManager.GetString("acceptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        internal static string access {
            get {
                return ResourceManager.GetString("access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the sufficient access to the selected location. iFodler can only be created in folder where you have access to read and write files. Please select a different location and try again..
        /// </summary>
        internal static string accessDenied {
            get {
                return ResourceManager.GetString("accessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also remove my membership.
        /// </summary>
        internal static string AlsoRemoveMembership {
            get {
                return ResourceManager.GetString("AlsoRemoveMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic sync.
        /// </summary>
        internal static string autoSync {
            get {
                return ResourceManager.GetString("autoSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set up.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string availableQuota {
            get {
                return ResourceManager.GetString("availableQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to share an encrypted iFolder. Only regular folders can be shared.
        /// </summary>
        internal static string cannotShareMessage {
            get {
                return ResourceManager.GetString("cannotShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot share iFolder.
        /// </summary>
        internal static string cannotShareTitle {
            get {
                return ResourceManager.GetString("cannotShareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for new iFolders....
        /// </summary>
        internal static string checkingForiFolders {
            get {
                return ResourceManager.GetString("checkingForiFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered while removing the iFolder..
        /// </summary>
        internal static string declineError {
            get {
                return ResourceManager.GetString("declineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;amp:Delete.
        /// </summary>
        internal static string deleteAction {
            get {
                return ResourceManager.GetString("deleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting directory: {0}.
        /// </summary>
        internal static string deleteClientDir {
            get {
                return ResourceManager.GetString("deleteClientDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting file:{0}.
        /// </summary>
        internal static string deleteClientFile {
            get {
                return ResourceManager.GetString("deleteClientFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This deletes the iFolder and its files from the server. Are you sure you sure you want to remove &quot;{0}&quot; form the server?.
        /// </summary>
        internal static string deleteiFolder {
            get {
                return ResourceManager.GetString("deleteiFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting on server: {0}.
        /// </summary>
        internal static string deleteUnknown {
            get {
                return ResourceManager.GetString("deleteUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server unavailable.
        /// </summary>
        internal static string disconnected {
            get {
                return ResourceManager.GetString("disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk quota.
        /// </summary>
        internal static string diskQuota {
            get {
                return ResourceManager.GetString("diskQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done checking for new iFolders.
        /// </summary>
        internal static string doneCheckingForiFolders {
            get {
                return ResourceManager.GetString("doneCheckingForiFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading directory: {0}.
        /// </summary>
        internal static string downloadDir {
            get {
                return ResourceManager.GetString("downloadDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file: {0}.
        /// </summary>
        internal static string downloadFile {
            get {
                return ResourceManager.GetString("downloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted.
        /// </summary>
        internal static string encrypted {
            get {
                return ResourceManager.GetString("encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iFolder Error.
        /// </summary>
        internal static string errorTitle {
            get {
                return ResourceManager.GetString("errorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you exit the Novell iFolder application, changes in your iFolder will no longer be tracked. The next ime you login, Novell iFolder will reconcile any differences between your iFolder and Server.
        /// </summary>
        internal static string exitMessage {
            get {
                return ResourceManager.GetString("exitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        internal static string exitTitle {
            get {
                return ResourceManager.GetString("exitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files/Folders to sync.
        /// </summary>
        internal static string filesnFolders {
            get {
                return ResourceManager.GetString("filesnFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then name of folder and iFolder must be the same.
        /// </summary>
        internal static string FolderDoesNotExistError {
            get {
                return ResourceManager.GetString("FolderDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can merge an iFolder only with a folder with same name. Select a folder with same name as the iFolder and try again.
        /// </summary>
        internal static string FolderDoesNotExistErrorDesc {
            get {
                return ResourceManager.GetString("FolderDoesNotExistErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder doesnot exist.
        /// </summary>
        internal static string FolderDoesNotExistErrorTitle {
            get {
                return ResourceManager.GetString("FolderDoesNotExistErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string freeSpaceUnits {
            get {
                return ResourceManager.GetString("freeSpaceUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered while reading iFolders.
        /// </summary>
        internal static string iFolderError {
            get {
                return ResourceManager.GetString("iFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read iFolders.
        /// </summary>
        internal static string iFolderErrorTitle {
            get {
                return ResourceManager.GetString("iFolderErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read iFolders.
        /// </summary>
        internal static string iFolderErrorTittle {
            get {
                return ResourceManager.GetString("iFolderErrorTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open iFolder {0}..
        /// </summary>
        internal static string iFolderOpenError {
            get {
                return ResourceManager.GetString("iFolderOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered while reverting the iFolder..
        /// </summary>
        internal static string iFolderRevertError {
            get {
                return ResourceManager.GetString("iFolderRevertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last sync time.
        /// </summary>
        internal static string lastSyncTime {
            get {
                return ResourceManager.GetString("lastSyncTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found change in directory: {0}.
        /// </summary>
        internal static string localDir {
            get {
                return ResourceManager.GetString("localDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found changes in file: {0}.
        /// </summary>
        internal static string localFile {
            get {
                return ResourceManager.GetString("localFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for changes: {0}.
        /// </summary>
        internal static string localSync {
            get {
                return ResourceManager.GetString("localSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log entries cleared..
        /// </summary>
        internal static string logEntriesCleared {
            get {
                return ResourceManager.GetString("logEntriesCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string logoff {
            get {
                return ResourceManager.GetString("logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from server.
        /// </summary>
        internal static string menuActionRemove {
            get {
                return ResourceManager.GetString("menuActionRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge &quot;{0}&quot; to ....
        /// </summary>
        internal static string mergeDescription {
            get {
                return ResourceManager.GetString("mergeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected location is on a network or non-physical drive. iFolders must reside on a physical drive. Please select a different location and try again..
        /// </summary>
        internal static string networkPath {
            get {
                return ResourceManager.GetString("networkPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of iFolders.
        /// </summary>
        internal static string noifolder {
            get {
                return ResourceManager.GetString("noifolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string notApplicable {
            get {
                return ResourceManager.GetString("notApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iFolder Open Error.
        /// </summary>
        internal static string openErrorTitle {
            get {
                return ResourceManager.GetString("openErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string owner {
            get {
                return ResourceManager.GetString("owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  contain a folder with the same name as the iFolder..
        /// </summary>
        internal static string PathDoesNotExist {
            get {
                return ResourceManager.GetString("PathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loation you selected already contains a folder with the same name as this iFolder. Please select a different location and try again..
        /// </summary>
        internal static string pathExistsError {
            get {
                return ResourceManager.GetString("pathExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected location includes the Program Files folder. The Program Files folder cannot contain an iFolder. Please select a different location and try again..
        /// </summary>
        internal static string PathIncludesProgFilesDirError {
            get {
                return ResourceManager.GetString("PathIncludesProgFilesDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected location includes the Windows folder. The Windows folder cannot contain an iFolder. Please select a different lcoation and try again..
        /// </summary>
        internal static string pathIncludesWinDirError {
            get {
                return ResourceManager.GetString("pathIncludesWinDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected location is inside another iFolder. iFolders connot exist inside other iFolders. Please select a different location and try again..
        /// </summary>
        internal static string pathIniFolderError {
            get {
                return ResourceManager.GetString("pathIniFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected location is inside the iFolder data folder. Please select a different location and try again..
        /// </summary>
        internal static string pathInStoreError {
            get {
                return ResourceManager.GetString("pathInStoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Location.
        /// </summary>
        internal static string pathInvalidErrorTitle {
            get {
                return ResourceManager.GetString("pathInvalidErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for changes.
        /// </summary>
        internal static string preSync {
            get {
                return ResourceManager.GetString("preSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This removes membership from iFolder and removes the iFolder from the list .
        /// </summary>
        internal static string RemoveMembershipMesg {
            get {
                return ResourceManager.GetString("RemoveMembershipMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove your membership from {0}.
        /// </summary>
        internal static string RemoveMembershipTitle {
            get {
                return ResourceManager.GetString("RemoveMembershipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove My Membership.
        /// </summary>
        internal static string RemoveMyMembership {
            get {
                return ResourceManager.GetString("RemoveMyMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete iFolder.
        /// </summary>
        internal static string removeTitle {
            get {
                return ResourceManager.GetString("removeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iFolder Revert Error.
        /// </summary>
        internal static string revertErrorTitle {
            get {
                return ResourceManager.GetString("revertErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide available iFolders.
        /// </summary>
        internal static string showiFolders {
            get {
                return ResourceManager.GetString("showiFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Conflicts.
        /// </summary>
        internal static string statusConflicts {
            get {
                return ResourceManager.GetString("statusConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized: {0}.
        /// </summary>
        internal static string statusSynced {
            get {
                return ResourceManager.GetString("statusSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete synchronization.
        /// </summary>
        internal static string statusSyncFailure {
            get {
                return ResourceManager.GetString("statusSyncFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing.
        /// </summary>
        internal static string statusSyncing {
            get {
                return ResourceManager.GetString("statusSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items to synchronize.
        /// </summary>
        internal static string statusSyncingItems {
            get {
                return ResourceManager.GetString("statusSyncingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items not synchronized.
        /// </summary>
        internal static string statusSyncItemsFailed {
            get {
                return ResourceManager.GetString("statusSyncItemsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string statusUnknown {
            get {
                return ResourceManager.GetString("statusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started synchronization: {0}.
        /// </summary>
        internal static string syncComplete {
            get {
                return ResourceManager.GetString("syncComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered while synchronizing the iFolder..
        /// </summary>
        internal static string syncError {
            get {
                return ResourceManager.GetString("syncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iFolder Synchronization Error.
        /// </summary>
        internal static string syncErrorTitle {
            get {
                return ResourceManager.GetString("syncErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iFolder Synchronization Error.
        /// </summary>
        internal static string syncErrorTittle {
            get {
                return ResourceManager.GetString("syncErrorTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started synchronization: {0}.
        /// </summary>
        internal static string synciFolder {
            get {
                return ResourceManager.GetString("synciFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing directory: {0}.
        /// </summary>
        internal static string syncingDir {
            get {
                return ResourceManager.GetString("syncingDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing file: {0}.
        /// </summary>
        internal static string syncingFile {
            get {
                return ResourceManager.GetString("syncingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading directory: {0}.
        /// </summary>
        internal static string uploadDir {
            get {
                return ResourceManager.GetString("uploadDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file: {0}.
        /// </summary>
        internal static string uploadFile {
            get {
                return ResourceManager.GetString("uploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        internal static string usedQuota {
            get {
                return ResourceManager.GetString("usedQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View available iFolders.
        /// </summary>
        internal static string viewAvailableiFolders {
            get {
                return ResourceManager.GetString("viewAvailableiFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to Connect.
        /// </summary>
        internal static string WaitConnect {
            get {
                return ResourceManager.GetString("WaitConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to synchronize.
        /// </summary>
        internal static string WaitSync {
            get {
                return ResourceManager.GetString("WaitSync", resourceCulture);
            }
        }
    }
}
