//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrayApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrayApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &quot;{0}&quot; to ....
        /// </summary>
        internal static string acceptDescription {
            get {
                return ResourceManager.GetString("acceptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while attempting to download the iFolder..
        /// </summary>
        internal static string acceptError {
            get {
                return ResourceManager.GetString("acceptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        internal static string access {
            get {
                return ResourceManager.GetString("access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the sufficient access to the selected location. iFodler can only be created in folder where you have access to read and write files. Please select a different location and try again..
        /// </summary>
        internal static string accessDenied {
            get {
                return ResourceManager.GetString("accessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also remove my membership.
        /// </summary>
        internal static string AlsoRemoveMembership {
            get {
                return ResourceManager.GetString("AlsoRemoveMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        internal static string authenticateError {
            get {
                return ResourceManager.GetString("authenticateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic sync.
        /// </summary>
        internal static string autoSync {
            get {
                return ResourceManager.GetString("autoSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set up.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available for download.
        /// </summary>
        internal static string availablefordownload {
            get {
                return ResourceManager.GetString("availablefordownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string availableQuota {
            get {
                return ResourceManager.GetString("availableQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string availableText {
            get {
                return ResourceManager.GetString("availableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string b {
            get {
                return ResourceManager.GetString("b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Back.
        /// </summary>
        internal static string backText {
            get {
                return ResourceManager.GetString("backText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B&amp;rowse.
        /// </summary>
        internal static string browseText {
            get {
                return ResourceManager.GetString("browseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string cancelText {
            get {
                return ResourceManager.GetString("cancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to share an encrypted iFolder. Only regular folders can be shared.
        /// </summary>
        internal static string cannotShareMessage {
            get {
                return ResourceManager.GetString("cannotShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot share iFolder.
        /// </summary>
        internal static string cannotShareTitle {
            get {
                return ResourceManager.GetString("cannotShareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checing for new iFolders....
        /// </summary>
        internal static string checkingForiFolders {
            get {
                return ResourceManager.GetString("checkingForiFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm passphrase:.
        /// </summary>
        internal static string confirmPassphrase {
            get {
                return ResourceManager.GetString("confirmPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered while removing the iFolder..
        /// </summary>
        internal static string declineError {
            get {
                return ResourceManager.GetString("declineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;amp:Delete.
        /// </summary>
        internal static string deleteAction {
            get {
                return ResourceManager.GetString("deleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting directory: {0}.
        /// </summary>
        internal static string deleteClientDir {
            get {
                return ResourceManager.GetString("deleteClientDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting file:{0}.
        /// </summary>
        internal static string deleteClientFile {
            get {
                return ResourceManager.GetString("deleteClientFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This deletes the iFolder and its files from the server. Are you sure you sure you want to remove &quot;{0}&quot; form the server?.
        /// </summary>
        internal static string deleteiFolder {
            get {
                return ResourceManager.GetString("deleteiFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting on server: {0}.
        /// </summary>
        internal static string deleteUnknown {
            get {
                return ResourceManager.GetString("deleteUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion In Progress.
        /// </summary>
        internal static string deletionInProgress {
            get {
                return ResourceManager.GetString("deletionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server unavailable.
        /// </summary>
        internal static string disconnected {
            get {
                return ResourceManager.GetString("disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk quota.
        /// </summary>
        internal static string diskQuota {
            get {
                return ResourceManager.GetString("diskQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk space available.
        /// </summary>
        internal static string diskSpaceAvailable {
            get {
                return ResourceManager.GetString("diskSpaceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk space used.
        /// </summary>
        internal static string diskSpaceUsed {
            get {
                return ResourceManager.GetString("diskSpaceUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the account for which the passphrase needs to be reset..
        /// </summary>
        internal static string domainSelectionFirst {
            get {
                return ResourceManager.GetString("domainSelectionFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domainSelectionPage.
        /// </summary>
        internal static string domainSelectionPageName {
            get {
                return ResourceManager.GetString("domainSelectionPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Next to proceed..
        /// </summary>
        internal static string domainSelectionPageSecond {
            get {
                return ResourceManager.GetString("domainSelectionPageSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select account.
        /// </summary>
        internal static string domainSelectionPageTitle {
            get {
                return ResourceManager.GetString("domainSelectionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done checking for new iFolders.
        /// </summary>
        internal static string doneCheckingForiFolders {
            get {
                return ResourceManager.GetString("doneCheckingForiFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading directory: {0}.
        /// </summary>
        internal static string downloadDir {
            get {
                return ResourceManager.GetString("downloadDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file: {0}.
        /// </summary>
        internal static string downloadFile {
            get {
                return ResourceManager.GetString("downloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address:.
        /// </summary>
        internal static string emailAddress {
            get {
                return ResourceManager.GetString("emailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encrypted key file was successfully exported..
        /// </summary>
        internal static string emailPageFirst {
            get {
                return ResourceManager.GetString("emailPageFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailPage.
        /// </summary>
        internal static string emailPageName {
            get {
                return ResourceManager.GetString("emailPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send this file to the administrator who will decrypt the key file and send it back to you. You can then use the decrypted key file to reset your passphrase using the second option of the wizard..
        /// </summary>
        internal static string emailPageSecond {
            get {
                return ResourceManager.GetString("emailPageSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old data file sent successfully. .
        /// </summary>
        internal static string emailPageTitle {
            get {
                return ResourceManager.GetString("emailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted.
        /// </summary>
        internal static string encrypted {
            get {
                return ResourceManager.GetString("encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption is not enabled for this account. Contact your system administrator to enable encryption..
        /// </summary>
        internal static string encryptionNotSet {
            get {
                return ResourceManager.GetString("encryptionNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Not Encrypted.
        /// </summary>
        internal static string encryptionNotSetHeading {
            get {
                return ResourceManager.GetString("encryptionNotSetHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enterPassphrasePage.
        /// </summary>
        internal static string enterPassphrasePageName {
            get {
                return ResourceManager.GetString("enterPassphrasePageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iFolder Error.
        /// </summary>
        internal static string errorTitle {
            get {
                return ResourceManager.GetString("errorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you exit the Novell iFolder application, changes in your iFolder will no longer be tracked. The next ime you login, Novell iFolder will reconcile any differences between your iFolder and Server.
        /// </summary>
        internal static string exitMessage {
            get {
                return ResourceManager.GetString("exitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        internal static string exitTitle {
            get {
                return ResourceManager.GetString("exitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Location to save old data file:.
        /// </summary>
        internal static string exportPageFilePath {
            get {
                return ResourceManager.GetString("exportPageFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the encrypted key file from the server and stores it locally..
        /// </summary>
        internal static string exportPageFirst {
            get {
                return ResourceManager.GetString("exportPageFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportPage.
        /// </summary>
        internal static string exportPageName {
            get {
                return ResourceManager.GetString("exportPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Recovery agent :.
        /// </summary>
        internal static string exportPageRA {
            get {
                return ResourceManager.GetString("exportPageRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtain old data file.
        /// </summary>
        internal static string exportPageTitle {
            get {
                return ResourceManager.GetString("exportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files/Folders to sync.
        /// </summary>
        internal static string filesnFolders {
            get {
                return ResourceManager.GetString("filesnFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!! You have successfully reset the passphrase.Now,you can use the new passphrase to access your data..
        /// </summary>
        internal static string finalPageFirst {
            get {
                return ResourceManager.GetString("finalPageFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finalPage.
        /// </summary>
        internal static string finalPageName {
            get {
                return ResourceManager.GetString("finalPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase is reset successfully..
        /// </summary>
        internal static string finalPageTitle {
            get {
                return ResourceManager.GetString("finalPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string finishText {
            get {
                return ResourceManager.GetString("finishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then name of folder and iFolder must be the same.
        /// </summary>
        internal static string FolderDoesNotExistError {
            get {
                return ResourceManager.GetString("FolderDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can merge an iFolder only with a folder with same name. Select a folder with same name as the iFolder and try again.
        /// </summary>
        internal static string FolderDoesNotExistErrorDesc {
            get {
                return ResourceManager.GetString("FolderDoesNotExistErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder doesnot exist.
        /// </summary>
        internal static string FolderDoesNotExistErrorTitle {
            get {
                return ResourceManager.GetString("FolderDoesNotExistErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder by same name already exists.
        /// </summary>
        internal static string Folderexists {
            get {
                return ResourceManager.GetString("Folderexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string freeSpaceUnits {
            get {
                return ResourceManager.GetString("freeSpaceUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string gb {
            get {
                return ResourceManager.GetString("gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string helpText {
            get {
                return ResourceManager.GetString("helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;iFolder account :.
        /// </summary>
        internal static string iFolderAcc {
            get {
                return ResourceManager.GetString("iFolderAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered while reading iFolders.
        /// </summary>
        internal static string iFolderError {
            get {
                return ResourceManager.GetString("iFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read iFolders.
        /// </summary>
        internal static string iFolderErrorTitle {
            get {
                return ResourceManager.GetString("iFolderErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read iFolders.
        /// </summary>
        internal static string iFolderErrorTittle {
            get {
                return ResourceManager.GetString("iFolderErrorTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open iFolder {0}..
        /// </summary>
        internal static string iFolderOpenError {
            get {
                return ResourceManager.GetString("iFolderOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered while reverting the iFolder..
        /// </summary>
        internal static string iFolderRevertError {
            get {
                return ResourceManager.GetString("iFolderRevertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reset passphrase. Try again..
        /// </summary>
        internal static string importErrorMesg {
            get {
                return ResourceManager.GetString("importErrorMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the &amp;above file encrypted?.
        /// </summary>
        internal static string importPageEncryCheck {
            get {
                return ResourceManager.GetString("importPageEncryCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Location of the new data file.
        /// </summary>
        internal static string importPageFilePathOne {
            get {
                return ResourceManager.GetString("importPageFilePathOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Passphrase is reset using the Decrypted key file..
        /// </summary>
        internal static string importPageFirstLine {
            get {
                return ResourceManager.GetString("importPageFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportPage.
        /// </summary>
        internal static string importPageName {
            get {
                return ResourceManager.GetString("importPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;One time password : .
        /// </summary>
        internal static string importPageOTP {
            get {
                return ResourceManager.GetString("importPageOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To recover a lost passphrase, you need the secret file (private key of the certificate) and the password to it or the data file from the administrator..
        /// </summary>
        internal static string infoPageFirst {
            get {
                return ResourceManager.GetString("infoPageFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfoPage.
        /// </summary>
        internal static string infoPageName {
            get {
                return ResourceManager.GetString("infoPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t have these parameters, you can use this wizard to export the old data file, which you can mail to your administrator who will decrypt and send it back to you. You can then use this new data file to reset your passphrase..
        /// </summary>
        internal static string infoPageSecond {
            get {
                return ResourceManager.GetString("infoPageSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Passphrase Recovery Wizard.
        /// </summary>
        internal static string infoPageTitle {
            get {
                return ResourceManager.GetString("infoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string kb {
            get {
                return ResourceManager.GetString("kb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last sync time.
        /// </summary>
        internal static string lastSyncTime {
            get {
                return ResourceManager.GetString("lastSyncTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found change in directory: {0}.
        /// </summary>
        internal static string localDir {
            get {
                return ResourceManager.GetString("localDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found changes in file: {0}.
        /// </summary>
        internal static string localFile {
            get {
                return ResourceManager.GetString("localFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for changes: {0}.
        /// </summary>
        internal static string localSync {
            get {
                return ResourceManager.GetString("localSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log entries cleared..
        /// </summary>
        internal static string logEntriesCleared {
            get {
                return ResourceManager.GetString("logEntriesCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log entries cleared..
        /// </summary>
        internal static string logEntriesCleared1 {
            get {
                return ResourceManager.GetString("logEntriesCleared1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate to the domain.You have been logged out of the account. Please login and try again..
        /// </summary>
        internal static string loginError {
            get {
                return ResourceManager.GetString("loginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string logoff {
            get {
                return ResourceManager.GetString("logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string mb {
            get {
                return ResourceManager.GetString("mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from server.
        /// </summary>
        internal static string menuActionRemove {
            get {
                return ResourceManager.GetString("menuActionRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &amp;from server.
        /// </summary>
        internal static string menuRemoveText {
            get {
                return ResourceManager.GetString("menuRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge &quot;{0}&quot; to ....
        /// </summary>
        internal static string mergeDescription {
            get {
                return ResourceManager.GetString("mergeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string na {
            get {
                return ResourceManager.GetString("na", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected location is on a network or non-physical drive. iFolders must reside on a physical drive. Please select a different location and try again..
        /// </summary>
        internal static string networkPath {
            get {
                return ResourceManager.GetString("networkPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New data file location is invalid.
        /// </summary>
        internal static string newDataFileError {
            get {
                return ResourceManager.GetString("newDataFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&amp;ew passphrase:.
        /// </summary>
        internal static string newPassphrase {
            get {
                return ResourceManager.GetString("newPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next.
        /// </summary>
        internal static string nextText {
            get {
                return ResourceManager.GetString("nextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of iFolders.
        /// </summary>
        internal static string noifolder {
            get {
                return ResourceManager.GetString("noifolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase not provided.
        /// </summary>
        internal static string noPassphrase {
            get {
                return ResourceManager.GetString("noPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string notApplicable {
            get {
                return ResourceManager.GetString("notApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not applicable.
        /// </summary>
        internal static string notApplicalbeText {
            get {
                return ResourceManager.GetString("notApplicalbeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select OK to merge or Cancel to select a different location.
        /// </summary>
        internal static string OkMergeCancel {
            get {
                return ResourceManager.GetString("OkMergeCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the location of an xml file..
        /// </summary>
        internal static string oldDataFileError {
            get {
                return ResourceManager.GetString("oldDataFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send old data file.
        /// </summary>
        internal static string oldDataFileNotSend {
            get {
                return ResourceManager.GetString("oldDataFileNotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iFolder Open Error.
        /// </summary>
        internal static string openErrorTitle {
            get {
                return ResourceManager.GetString("openErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string owner {
            get {
                return ResourceManager.GetString("owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The values in the new and confirm passphrase fields do not match..
        /// </summary>
        internal static string passphraseNotEqualError {
            get {
                return ResourceManager.GetString("passphraseNotEqualError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase is not set for this account..
        /// </summary>
        internal static string passphraseNotSet {
            get {
                return ResourceManager.GetString("passphraseNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase Not Set.
        /// </summary>
        internal static string passphraseNotSetHeading {
            get {
                return ResourceManager.GetString("passphraseNotSetHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Password:.
        /// </summary>
        internal static string passwordText {
            get {
                return ResourceManager.GetString("passwordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  contain a folder with the same name as the iFolder..
        /// </summary>
        internal static string PathDoesNotExist {
            get {
                return ResourceManager.GetString("PathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loation you selected already contains a folder with the same name as this iFolder. Please select a different location and try again..
        /// </summary>
        internal static string pathExistsError {
            get {
                return ResourceManager.GetString("pathExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected location includes the Program Files folder. The Program Files folder cannot contain an iFolder. Please select a different location and try again..
        /// </summary>
        internal static string PathIncludesProgFilesDirError {
            get {
                return ResourceManager.GetString("PathIncludesProgFilesDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected location includes the Windows folder. The Windows folder cannot contain an iFolder. Please select a different lcoation and try again..
        /// </summary>
        internal static string pathIncludesWinDirError {
            get {
                return ResourceManager.GetString("pathIncludesWinDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected location is inside another iFolder. iFolders connot exist inside other iFolders. Please select a different location and try again..
        /// </summary>
        internal static string pathIniFolderError {
            get {
                return ResourceManager.GetString("pathIniFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected location is inside the iFolder data folder. Please select a different location and try again..
        /// </summary>
        internal static string pathInStoreError {
            get {
                return ResourceManager.GetString("pathInStoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Location.
        /// </summary>
        internal static string pathInvalidErrorTitle {
            get {
                return ResourceManager.GetString("pathInvalidErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for changes.
        /// </summary>
        internal static string preSync {
            get {
                return ResourceManager.GetString("preSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reset passphrase. You have been logged out of the account.Please login and try again..
        /// </summary>
        internal static string recoveryError {
            get {
                return ResourceManager.GetString("recoveryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string regular {
            get {
                return ResourceManager.GetString("regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This removes membership from iFolder and removes the iFolder from the list .
        /// </summary>
        internal static string RemoveMembershipMesg {
            get {
                return ResourceManager.GetString("RemoveMembershipMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove your membership from {0}.
        /// </summary>
        internal static string RemoveMembershipTitle {
            get {
                return ResourceManager.GetString("RemoveMembershipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove My Membership.
        /// </summary>
        internal static string RemoveMyMembership {
            get {
                return ResourceManager.GetString("RemoveMyMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove my Mem&amp;bership.
        /// </summary>
        internal static string RemoveMyMembershipText {
            get {
                return ResourceManager.GetString("RemoveMyMembershipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete iFolder.
        /// </summary>
        internal static string removeTitle {
            get {
                return ResourceManager.GetString("removeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase reset failed.
        /// </summary>
        internal static string resetPassphraseError {
            get {
                return ResourceManager.GetString("resetPassphraseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iFolder Revert Error.
        /// </summary>
        internal static string revertErrorTitle {
            get {
                return ResourceManager.GetString("revertErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of secret file is invalid.
        /// </summary>
        internal static string secretPathInvalid {
            get {
                return ResourceManager.GetString("secretPathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can exit the wizard at any step and work on subsequent steps later by using this page         .
        /// </summary>
        internal static string selectionPageFive {
            get {
                return ResourceManager.GetString("selectionPageFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;I have no secret file or data file..
        /// </summary>
        internal static string selectionPageFour {
            get {
                return ResourceManager.GetString("selectionPageFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectionPage.
        /// </summary>
        internal static string selectionPageName {
            get {
                return ResourceManager.GetString("selectionPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option to recover your passphrase..
        /// </summary>
        internal static string selectionPageOne {
            get {
                return ResourceManager.GetString("selectionPageOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have the &amp;secret file and the password to it.
        /// </summary>
        internal static string selectionPageSecond {
            get {
                return ResourceManager.GetString("selectionPageSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have the new &amp;data file sent by the administrator..
        /// </summary>
        internal static string selectionPageThird {
            get {
                return ResourceManager.GetString("selectionPageThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Passphrase Recovery step.
        /// </summary>
        internal static string selectionPageTitle {
            get {
                return ResourceManager.GetString("selectionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server_Default.
        /// </summary>
        internal static string serverDefaultRA {
            get {
                return ResourceManager.GetString("serverDefaultRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set New Passphrase.
        /// </summary>
        internal static string setNewPassphraseTitle {
            get {
                return ResourceManager.GetString("setNewPassphraseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide available iFolders.
        /// </summary>
        internal static string showiFolders {
            get {
                return ResourceManager.GetString("showiFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a single account. Click Next to proceed..
        /// </summary>
        internal static string singleAccountText {
            get {
                return ResourceManager.GetString("singleAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingleWizPage.
        /// </summary>
        internal static string singleWizName {
            get {
                return ResourceManager.GetString("singleWizName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Location  of secret file: .
        /// </summary>
        internal static string singleWizP12File {
            get {
                return ResourceManager.GetString("singleWizP12File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase is reset using the secret file and its password..
        /// </summary>
        internal static string singleWizPageFirst {
            get {
                return ResourceManager.GetString("singleWizPageFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingleWizPage.
        /// </summary>
        internal static string singleWizPageName {
            get {
                return ResourceManager.GetString("singleWizPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Secret file password:.
        /// </summary>
        internal static string singleWizPasswd {
            get {
                return ResourceManager.GetString("singleWizPasswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Conflicts.
        /// </summary>
        internal static string statusConflicts {
            get {
                return ResourceManager.GetString("statusConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized: {0}.
        /// </summary>
        internal static string statusSynced {
            get {
                return ResourceManager.GetString("statusSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete synchronization.
        /// </summary>
        internal static string statusSyncFailure {
            get {
                return ResourceManager.GetString("statusSyncFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing.
        /// </summary>
        internal static string statusSyncing {
            get {
                return ResourceManager.GetString("statusSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items to synchronize.
        /// </summary>
        internal static string statusSyncingItems {
            get {
                return ResourceManager.GetString("statusSyncingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items not synchronized.
        /// </summary>
        internal static string statusSyncItemsFailed {
            get {
                return ResourceManager.GetString("statusSyncItemsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string statusUnknown {
            get {
                return ResourceManager.GetString("statusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuccessPage.
        /// </summary>
        internal static string successPageName {
            get {
                return ResourceManager.GetString("successPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started synchronization: {0}.
        /// </summary>
        internal static string syncComplete {
            get {
                return ResourceManager.GetString("syncComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization disabled.
        /// </summary>
        internal static string syncDisabled {
            get {
                return ResourceManager.GetString("syncDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered while synchronizing the iFolder..
        /// </summary>
        internal static string syncError {
            get {
                return ResourceManager.GetString("syncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iFolder Synchronization Error.
        /// </summary>
        internal static string syncErrorTitle {
            get {
                return ResourceManager.GetString("syncErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iFolder Synchronization Error.
        /// </summary>
        internal static string syncErrorTittle {
            get {
                return ResourceManager.GetString("syncErrorTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started synchronization: {0}.
        /// </summary>
        internal static string synciFolder {
            get {
                return ResourceManager.GetString("synciFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing directory: {0}.
        /// </summary>
        internal static string syncingDir {
            get {
                return ResourceManager.GetString("syncingDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing file: {0}.
        /// </summary>
        internal static string syncingFile {
            get {
                return ResourceManager.GetString("syncingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails.
        /// </summary>
        internal static string thumbnails {
            get {
                return ResourceManager.GetString("thumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtain old data file.Try again.
        /// </summary>
        internal static string unableToExportMesg {
            get {
                return ResourceManager.GetString("unableToExportMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        internal static string Unlimited {
            get {
                return ResourceManager.GetString("Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading directory: {0}.
        /// </summary>
        internal static string uploadDir {
            get {
                return ResourceManager.GetString("uploadDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file: {0}.
        /// </summary>
        internal static string uploadFile {
            get {
                return ResourceManager.GetString("uploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to used.
        /// </summary>
        internal static string used {
            get {
                return ResourceManager.GetString("used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        internal static string usedQuota {
            get {
                return ResourceManager.GetString("usedQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        internal static string userNameText {
            get {
                return ResourceManager.GetString("userNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string verifyText {
            get {
                return ResourceManager.GetString("verifyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View available iFolders.
        /// </summary>
        internal static string viewAvailableiFolders {
            get {
                return ResourceManager.GetString("viewAvailableiFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to Connect.
        /// </summary>
        internal static string WaitConnect {
            get {
                return ResourceManager.GetString("WaitConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to synchronize.
        /// </summary>
        internal static string WaitSync {
            get {
                return ResourceManager.GetString("WaitSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passphraseRecoveryWizard.
        /// </summary>
        internal static string wizardName {
            get {
                return ResourceManager.GetString("wizardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase Recovery Wizard.
        /// </summary>
        internal static string wizardText {
            get {
                return ResourceManager.GetString("wizardText", resourceCulture);
            }
        }
    }
}
