#ifndef _CFFSDEFINES_H_
#define _CFFSDEFINES_H_

#define SHORT_DIRECTORY_HANDLE_FLAG   0x00
#define DIRECTORY_BASE_FLAG             0x01
#define NO_HANDLE_FLAG                  0xFF

#define NO_HUGE_DATA   					2

#define NWSM_OVERWRITE_DATA_SET								0x0001
#define NWSM_DO_NOT_OVERWRITE_DATA_SET						0x0002




#define FS_CFS_READ_ONLY                 			READ_ONLY_BIT	
#define FS_CFS_HIDDEN                    			HIDDEN_BIT				
#define FS_CFS_SYSTEM                    			SYSTEM_BIT				
#define FS_CFS_EXECUTE_ONLY              			EXECUTE_BIT				
#define FS_CFS_SUBDIRECTORY                 		SUBDIRECTORY_BIT			
#define FS_CFS_ARCHIVE                   			ARCHIVE_BIT				
#define FS_CFS_SHAREABLE                  			SHAREABLE_BIT			
#define FS_CFS_TRANSACTION               			TRANSACTION_BIT			
#define FS_CFS_READ_AUDIT                			READ_AUDIT_BIT			
#define FS_CFS_WRITE_AUDIT               			WRITE_AUDIT_BIT			
#define FS_CFS_PURGE                     			IMMEDIATE_PURGE_BIT		
#define FS_CFS_RENAME_INHIBIT            			RENAME_INHIBIT_BIT		
#define FS_CFS_DELETE_INHIBIT            			DELETE_INHIBIT_BIT		
#define FS_CFS_COPY_INHIBIT              			COPY_INHIBIT_BIT		 	   
#define FS_CFS_NO_SUBALLOC							NO_SUBALLOC_BIT		
#define FS_CFS_REMOTE_DATA_ACCESS      				REMOTE_DATA_ACCESS_BIT
#define FS_CFS_REMOTE_DATA_INHIBIT     				REMOTE_DATA_INHIBIT_BIT
#define FS_CFS_COMPRESS_FILE_IMMEDIATE 				COMPRESS_FILE_IMMEDIATELY_BIT
#define FS_CFS_DATA_STREAM_IS_COMPRESSED 			DATA_STREAM_IS_COMPRESSED_BIT
#define FS_CFS_DO_NOT_COMPRESS_FILE    				DO_NOT_COMPRESS_FILE_BIT
#define FS_CFS_CANT_COMPRESS_DATA      				CANT_COMPRESS_DATA_STREAM_BIT
#define FS_CFS_OBJ_ARCHIVE_BIT  					ATTR_ARCHIVE_BIT
#define FS_CFS_REMOTE_DATA_SAVE_KEY_BIT   			REMOTE_DATA_SAVE_KEY_BIT


#define FS_CFS_READ_ACCESS     				 				READ_ACCESS_BIT
#define FS_CFS_WRITE_ACCESS	 				 				WRITE_ACCESS_BIT
#define FS_CFS_DENY_READ_ACCESS	 			 				DENY_READ_BIT
#define FS_CFS_DENY_WRITE_ACCESS 			 				DENY_WRITE_BIT
#define FS_CFS_COMPATABILITY_MODE_BIT    					COMPATABILITY_MODE_BIT
#define FS_CFS_FILE_WRITE_THROUGH_BIT	   			 		FILE_WRITE_THROUGH_BIT
#define FS_CFS_FILE_READ_THROUGH_BIT	     		  		FILE_READ_THROUGH_BIT
#define FS_CFS_LEAVE_FILE_COMPRESSED_BIT 					LEAVE_FILE_COMPRESSED_BIT 
#define FS_CFS_DELETE_FILE_ON_CLOSE_BIT		 				DELETE_FILE_ON_CLOSE_BIT// should not be used
#define FS_CFS_ALWAYS_READ_AHEAD_BIT		 				ALWAYS_READ_AHEAD_BIT // should not be used
#define FS_CFS_NEVER_READ_AHEAD_BIT			 				NEVER_READ_AHEAD_BIT // should not be used
#define FS_CFS_NO_RIGHTS_CHECK_ON_OPEN_BIT					NO_RIGHTS_CHECK_ON_OPEN_BIT
#define FS_CFS_ENABLE_IO_ON_COMPRESSED_DATA_BIT				ENABLE_IO_ON_COMPRESSED_DATA_BIT
#define FS_CFS_NO_UPDATE_LAST_ACCESSED_ON_CLOSE				NO_UPDATE_LAST_ACCESSED_ON_CLOSE_BIT


#define FS_CFS_OPEN_FILE							OPEN_FILE
#define FS_CFS_TRUNCATE_FILE	 				    TRUNCATE_FILE
#define FS_CFS_CREATE_FILE	 						CREATE_FILE
#define FS_CFS_RO_ACCESS_OK 						RO_ACCESS_OK
#define FS_CFS_OPEN_CALLBACK						OPEN_CALLBACK




#define FS_CFS_MODIFY_NAME                 			MName					
#define FS_CFS_MODIFY_ATTRIBUTES           			MAttributes			
#define FS_CFS_MODIFY_CREATION_DATE        			MCreationDate		
#define FS_CFS_MODIFY_CREATION_TIME        			MCreationTime		
#define FS_CFS_MODIFY_CREATOR_ID           			MCreatorID			
#define FS_CFS_MODIFY_ARCHIVE_DATE         			MArchiveDate			
#define FS_CFS_MODIFY_ARCHIVE_TIME         			MArchiveTime			
#define FS_CFS_MODIFY_ARCHIVER_ID          			MArchiveID			
#define FS_CFS_MODIFY_MODIFY_DATE          			MModifyDate			
#define FS_CFS_MODIFY_MODIFY_TIME          			MModifyTime			
#define FS_CFS_MODIFY_MODIFIER_ID          			MModifyID			
#define FS_CFS_MODIFY_ACCESSED_DATE        			MLastAccess			
#define FS_CFS_MODIFY_RIGHTS_MASK          			MRestrict			
#define FS_CFS_MODIFY_MAXIMUM_SPACE        			MMaxSpace			

#endif /* _CFFSDEFINES_H_ */
