#!/bin/bash

         
#*******        Description of variables        *******
# ifolder_root : location from where the sources are picked and packaged to ifolder3.7.1.pkg.
#
# ifolder_resources : location from where the welcome page, background image gets picked for the package. 
# This dir should contain the Welcome.rtf, background image, Readme.txt etc
# ifolder_plists : location where Info.plist and Description.plist is available
# ifolder_destination_package : Location where the .pkg is created   
#******************************************************

export ifolder_root=/ifoldertemp
export ifolder_destination_package=~/Desktop/ifpackage
export ifolder_resources=$(pwd)/ifresources
export ifolder_plists=$(pwd)/client-pkg

package_name=iFolder3.pkg
diskimage_name=ifolder3-mac.dmg
volume_name=ifolder-3.7.1-1

#First look to see if $PACKAGEMAKER is set and exists and use that if so.
#Otherwise, look in other standard locations
for i in "$PACKAGEMAKER" \
         "/Developer/usr/bin/packagemaker" \
	 "/Developer/Tools/packagemaker"; do
	if [ -n "$i" -a -f "$i" ]; then
		PACKAGEMAKER="$i"
		break
	fi
done

if [ -z "$PACKAGEMAKER" ]; then
	echo "Can't find packagemaker"
	exit 1
fi

echo "Using PACKAGEMAKER=$PACKAGEMAKER"
if [ -d $ifolder_destination_package ]
        then
       sudo rm -rf $ifolder_destination_package 
        fi

mkdir -p $ifolder_destination_package

echo "Initiating iFolder package"

sudo $PACKAGEMAKER -build -p "$ifolder_destination_package/$package_name" -f "$ifolder_root" -ds -v -r "$ifolder_resources" -i "$ifolder_plists/Info.plist" -d "$ifolder_plists/Description.plist"

echo "Completed iFolder package"
echo "Initiating disk image operation"

sudo hdiutil create -srcfolder $ifolder_destination_package -volname $volume_name ~/Desktop/$diskimage_name
echo "Completed disk image operation"
